# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: SCiarella <simoneciarella@gmail.com>
CodeOfConductContact: simoneciarella@gmail.com
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: SCiarella
MarkdownIndentation: 2
PackageName: AttentionLayer
PackageOwner: DEEPDIP-project
PackageUUID: 3ee63b08-73c5-50c8-acc9-f395aa68c39a
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
